#define MINIMUM_ADC_VALUE     0
#define MAXIMUM_ADC_VALUE     1023
#define MINIMUM_SLOPE_VALUE   1
#define MAXIMUM_SLOPE_VALUE   10

#define TGRILL_OFF  0
#define TGRILL_ON   250

#define NO_TEMP_GOAL -1

#define TX_ID_TEMP 0x00
